language: csharp
dist: trusty

# keep this in sync with the value in global.json
dotnet: 2.1.201

matrix:
  include:
    - mono: stable
      env: USE_DOTNET_CLI=1
      os: linux
    - mono: latest
      env: USE_DOTNET_CLI=1
      os: osx
    - mono: stable
      env: USE_MSBUILD=1
      os: linux
    - mono: latest
      env: USE_MSBUILD=1
      os: osx
    - mono: latest
      env: USE_MSBUILD=1
      os: linux
    - mono: weekly
      env: USE_MSBUILD=1
      os: linux
      
sudo: true  # use the new container-based Travis infrastructure

script:
  - ./build.sh Pack
